INSERT INTO node_types (id, name) VALUES
    (10, 'Paragraph'),
    (11, 'BlockQuote'),
    (12, 'HtmlBlock'),
    (13, 'CodeInline'),
    (14, 'TableHead'),
    (15, 'TableRow'),
    (16, 'TableCell'),
    (17, 'Emphasis'),
    (18, 'Strong'),
    (19, 'Strikethrough'),
    (20, 'Superscript'),
    (21, 'Subscript'),
    (22, 'FootnoteDefinition'),
    (23, 'FootnoteReference'),
    (24, 'DefinitionList'),
    (25, 'DefinitionListTitle'),
    (26, 'DefinitionListDefinition'),
    (27, 'MetadataBlock'),
    (28, 'MathInline'),
    (29, 'MathDisplay'),
    (30, 'HtmlInline'),
    (31, 'HorizontalRule')
ON CONFLICT(id) DO NOTHING;
