export const labels = {
  language: "Language",
  languageEnglish: "English",
  languageZhCN: "中文",
  workspace: "Workspace",
  welcomeTitle: "Welcome to Tauri + Solid",
  learnMore: "Click on the Tauri, Vite, and Solid logos to learn more.",
  greet: "Greet",
  enterName: "Enter a name...",
  close: "Close",
  floatingEditorPanelTitle: "Floating Editor Panel",
  floatingEditorPanelPlaceholder: "Type here...",
  contentTypeNote: "Note",
  contentTypeOutline: "Outline",
  contentTypeMarkmap: "Markmap",
  editorInputMarkdownText: "Markdown Text",
  editorInputWysiwyg: "WYSIWYG",
  editorInputMarkmap: "Markmap",
  navigation: "Navigation",
  files: "Files",
  tree: "Tree",
  recent: "Recent",
  recentToday: "Today",
  recentWeek: "Last 7 days",
  recentOlder: "Earlier",
  favorites: "Favorites",
  tags: "Tags",
  search: "Search",
  loading: "Loading",
  settings: "Settings",
  addNote: "Add note",
  showSidebar: "Show sidebar",
  hideSidebar: "Hide sidebar",
  emptyState: "No content yet. Create your first item."
} as const;
